apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-havenbridge-api-to-postgres
  namespace: havenbridge
  labels:
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: havenbridge

spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/instance: havenbridge-postgres
      app.kubernetes.io/name: postgresql

  policyTypes:
    - Ingress

  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: havenbridge
          podSelector:
            matchLabels:
              app.kubernetes.io/name: havenbridge-api

      ports:
        - protocol: TCP
          port: 5432
