---
# Ansible inventory for the Ever Presence Haven Kubernetes lab.

all:
  vars:
    # Linux account created by cloud-init.
    ansible_user: mino

    # Private key used to connect to the VMs.
    ansible_ssh_private_key_file: /home/alabi/.ssh/eph_k8s

    # Python interpreter available on Ubuntu.
    ansible_python_interpreter: /usr/bin/python3

  children:
    control_plane:
      hosts:
        eph-cp01:
          ansible_host: 172.16.10.31

        eph-cp02:
          ansible_host: 172.16.10.32

        eph-cp03:
          ansible_host: 172.16.10.33

    workers:
      hosts:
        eph-worker01:
          ansible_host: 172.16.10.34

        eph-worker02:
          ansible_host: 172.16.10.35

    cd_runners:
      hosts:
        havenbridge-runner01:
          ansible_host: 172.16.10.37
