---
# Deploy the kube-vip static Pod manifest to Kubernetes
# control-plane nodes.
#
# The --limit option can be used to deploy kube-vip to one
# control-plane node at a time.
#
# Examples:
#
#   ansible-playbook playbooks/prepare_kube_vip.yml \
#     --limit eph-cp02
#
#   ansible-playbook playbooks/prepare_kube_vip.yml \
#     --limit eph-cp03

- name: Prepare kube-vip on control-plane nodes
  hosts: control_plane
  become: true
  gather_facts: false

  roles:
    - role: kube_vip
