[pytest]
# Search for tests only inside the tests directory.
testpaths = tests

# Recognize Python files whose names begin with test_.
python_files = test_*.py

# Recognize functions whose names begin with test_.
python_functions = test_*

# Display additional information for skipped, failed, and errored tests.
addopts = -ra
